targets:
  $default:
    builders:
      hemend_builder|annotations:
        enabled: true
      

builders:
  hemend_builder:
    target: ":hemend_builder"
    import: "package:hemend/builders/builders.dart"
    builder_factories: ["generatePostMethod"]
    build_extensions: { ".dart": [".hemend.dart"] }
    auto_apply: all_packages
    build_to: source
    applies_builders: ["source_gen|combining_builder"]