name: hemend
description: base package of Hemend projects
version: 0.0.1
homepage: https://hemend.com/

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^3.2.3
  package_info_plus: ^1.4.2
  http:
  shared_preferences: ^2.0.13

  dio: ^4.0.1
  web_socket_channel: ^2.1.0
  path_provider: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
