name: hemend
description: base package of Hemend projects
version: 0.1.3
homepage: https://hemend.com/

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  device_info_plus: ^8.1.0
  flutter:
    sdk: flutter
  dio: null
  package_info_plus: ^3.0.2
  path_provider: ^2.0.11
  rxdart: ^0.27.4
  shared_preferences: ^2.0.13
  web_socket_channel: ^2.1.0
  flutter_bloc: ^8.1.2
  animations: ^2.0.7
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter: null
