name: hemend
description: base package of Hemend projects
version: 0.1.2
homepage: https://hemend.com/

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  device_info_plus: ^3.2.3
  flutter:
    sdk: flutter
  http: null
  package_info_plus: ^1.4.2
  path_provider: ^2.0.11
  rive: ^0.8.4
  rxdart: ^0.27.4
  shared_preferences: ^2.0.13
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter: null
