name: hemend
description: base package of Hemend projects
version: 0.1.3
homepage: https://hemend.com/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: null
  path_provider: ^2.0.11
  rxdart: ^0.27.4
  flutter_bloc: ^8.1.2
  animations: ^2.0.7
  equatable: ^2.0.5
  hemend_logger: ^0.3.0+1
  hydrated_bloc: ^9.1.4

dev_dependencies:
  moti_lints: ^1.1.3
  flutter_test:
    sdk: flutter

flutter: null
